### ISSUE TITLE
genshin.profile: 截图时指定合适的页面宽度

### ISSUE THREAD

**Issue by undefined-moe** [koishijs/koishi-plugin-genshin#11]
当前页面宽度取决于 puppeteer 设置的 viewport，应当在截图前进行 `setViewport()` （太宽了真的好丑啊

![image](https://user-images.githubusercontent.com/29992205/148056589-19635673-4fce-4d01-a696-1385d1a25b0e.png)

**Comment by dragon-fish** [comment]
~这不正意味着响应式设计做的好吗，不论什么宽度都能正常显示~

之后我找时间看看多加一个配置项
