### ISSUE TITLE
沙盒中help genshin指令未找到

### ISSUE THREAD

**Issue by devil233-ui** [koishijs/koishi-plugin-genshin#12]
![QQ截图20230916135542](https://github.com/koishijs/koishi-plugin-genshin-legacy/assets/69190444/93242af8-784a-4c1a-8a62-e09fb62808cf)
![QQ截图20230916135747](https://github.com/koishijs/koishi-plugin-genshin-legacy/assets/69190444/2b352080-0f18-400e-a876-ca474a0175a7)

使用两种方法的安装情况似乎都正常（？），koishi的日志也没有报错
**npm**
> C:\Users\Administrator>npm install koishi-plugin-genshin
added 133 packages, and changed 7 packages in 19s
19 packages are looking for funding
  run `npm fund` for details

**yarn**
> C:\Users\Administrator>yarn add koishi-plugin-genshin
> yarn add v1.22.19
> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> [3/4] Linking dependencies...
> warning " > koishi-plugin-genshin@2.0.0-beta.15" has unmet peer dependency "koishi-core@^3.11.1".
> [4/4] Building fresh packages...
> success Saved 1 new dependency.
> info Direct dependencies
> └─ koishi-plugin-genshin@2.0.0-beta.15
> info All dependencies
> └─ koishi-plugin-genshin@2.0.0-beta.15
> Done in 3.21s.

**Comment by dragon-fish** [comment]
此插件不支持 Koishi v4 且暂无适配的计划
