### ISSUE TITLE
linux chromium 截图不全

### ISSUE THREAD

**Issue by undefined-moe** [koishijs/koishi-plugin-genshin#8]
![image](https://user-images.githubusercontent.com/29992205/129774641-087550d0-f7e4-4456-992d-5932f613aae6.png)

建议的解决方案：截图前将 `viewport` 调至页面高度

**Comment by dragon-fish** [comment]
啊这……因为环境问题我不方便测试，欢迎 PR

**Comment by undefined-moe** [comment]
request(perm)

**Comment by undefined-moe** [comment]
算了你自己看着merge吧 我跑路了

https://gitpod.io#snapshot/ce39141a-ad0d-43b5-bb78-3dae68537805

**Comment by dragon-fish** [comment]
已解决
